name: Cloudflare Deployment

on:
  push:
    branches:
      - main
    paths:
      - "src/content/**"
      - ".github/workflows/cloudflare-deployment.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_BRANCH_FLAG: ${{ github.ref_name == 'dev' && '--branch=dev' || '' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Cloudflare
        run: |
          echo "Deploying with flag: $DEPLOY_BRANCH_FLAG"
          npx wrangler pages deploy ./dist --project-name=portfolio $DEPLOY_BRANCH_FLAG --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          DEPLOY_BRANCH_FLAG: ${{ github.ref_name == 'dev' && '--branch=dev' || '' }}